### ISSUE TITLE
Why the scale in config is 24?

### ISSUE THREAD

**Issue by JacobKong** [Pilhyeon/BaSNet-pytorch#5]
Dear author

Why the scale in config is 24? What is the meaning of scale?

Thanks a lot!

**Comment by Pilhyeon** [comment]
We use the scale factor in order to produce more precise decisions as [STPN](https://github.com/bellos1203/STPN) did.

For example, CAS with length 750 is upscaled to that of length 750*24=18k with linear interpolation, then it is thresholded.

This enables us to make more suitable predictions because the number of logical segments largely increases.

**Comment by JacobKong** [comment]
Thanks a lot!

**Comment by jun0wanan** [comment]
> We use the scale factor in order to produce more precise decisions as [STPN](https://github.com/bellos1203/STPN) did.
> 
> For example, CAS with length 750 is upscaled to that of length 750*24=18k with linear interpolation, then it is thresholded.
> 
> This enables us to make more suitable predictions because the number of logical segments largely increases.

hi,  

       t_factor = (16 * v_len) / (scale * num_segments * sampling_frames)   why you do that ?~
